IssueManager/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IssueManager.Data;
using IssueManager.Models;
using IssueManager.Static_classes;
using System.Linq.Expressions;

namespace IssueManager.Controllers
{
    public class CommentsController : Controller
    {
        private readonly IssueManagerContext _context;

        public CommentsController(IssueManagerContext context)
        {
            _context = context;
        }

        // GET: Comments
        public async Task<IActionResult> Index(int? issueId, string search/*, bool? byTitle*/, string sort)
        {
            ViewData["issueId"] = issueId;
            // providing this value here instead of determining it in view, because view cannot do it if there isn't any issue in result sequence
            ViewData["issueName"] = issueId is null ? "All issues" : _context.Issue.Find(issueId).Title;


            ViewData["search"] = search;
            // empty string means no filtering
                Expression<Func<Comment, bool>> searchPredicate = c => string.IsNullOrEmpty(search) || c.Content.Contains(search);
			return View(
                await _context.Comment
                .Include(c => c.Issue)
                .Where(c => issueId == null || c.Issue.Id == issueId)
                .Where(searchPredicate)
                .OrderBy(c => c.SubmitDate)
                .ToListAsync()
             );
        }

        // GET: Comments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await _context.Comment
                .Include(c => c.Issue)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comment == null)
            {
                return NotFound();
            }

            return View(comment);
        }

        // GET: Comments/Create
        public async Task<IActionResult> Create(int? issueId)
        {
            if (issueId is null)
            {
                //this.SetTemporaryMessage("Cannot create a comment not referencing any issue. Go to issues page, select comments from there, and try again.", Constants.BootstrapMsgType.Danger);
                //return RedirectToAction(nameof(Index));
            }
            //ViewData["issueId"] = issueId;
            // assign SelectList of issues (key is id, value is issue name) to ViewBag
            ViewBag.IssueId = await _context.Issue.Select(i => new SelectListItem { Value = i.Id.ToString(), Text = i.Title }).ToListAsync();
            return View();
        }

        // POST: Comments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Author,Content")] Comment comment)
        {
            if (new[] {nameof(Comment.Author), nameof(Comment.Content)}.All(s => ModelState.IsFieldValid(s)))
            {
                if (!int.TryParse(Request.Form["Issue.Id"], out int issueId))
                {
                    this.SetTemporaryMessage("Provided issue ID is not a number or is invalid number.", Constants.BootstrapMsgType.Danger);
                    return RedirectToAction(nameof(Index));
                }
                comment.SubmitDate = DateTime.Now;
                comment.Issue = await _context.Issue.FindAsync(issueId);
                _context.Add(comment);
                await _context.SaveChangesAsync();
                this.SetTemporaryMessage("Comment created successfully.", Constants.BootstrapMsgType.Success);
                return RedirectToAction(nameof(Index), new { issueId = issueId });
            }
            return View(comment);
        }

        // GET: Comments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await _context.Comment.FindAsync(id);
            if (comment == null)
            {
                return NotFound();
            }
            return View(comment);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("Author,Content,SubmitDate")] Comment comment)
        {
            int id = Convert.ToInt32(Request.Form["Id"]);
            Comment commentInDb = await _context.Comment.FindAsync(id);
            if (commentInDb == null)
			{
				return NotFound();
			}

            if (new[] { nameof(Comment.Author), nameof(Comment.Content), nameof(Comment.SubmitDate) }.All(s => ModelState.IsFieldValid(s)))
            {
				try
				{
					commentInDb.Author = comment.Author;
					commentInDb.Content = comment.Content;
					commentInDb.SubmitDate = comment.SubmitDate;
					_context.Update(commentInDb);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!CommentExists(commentInDb.Id)) // probably useless (id is checked above), but I'll leave it
					{
                        this.SetTemporaryMessage("Comment was not updated due to invalid data.", Constants.BootstrapMsgType.Danger);
						return NotFound();
					}
					else
					{
						throw;
					}
				}
                this.SetTemporaryMessage("Comment updated successfully.", Constants.BootstrapMsgType.Success);
				return RedirectToAction(nameof(Index));
			}
            else
			{
				this.SetTemporaryMessage("Comment was not updated due to invalid data.", Constants.BootstrapMsgType.Danger);
				return View(comment);
            }
        }

        // GET: Comments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await _context.Comment
                .Include(c => c.Issue)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comment == null)
            {
                return NotFound();
            }

            return View(comment);
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var comment = await _context.Comment.FindAsync(id);
            if (comment != null)
            {
                _context.Comment.Remove(comment);
                await _context.SaveChangesAsync();
                this.SetTemporaryMessage("Comment deleted successfully.", Constants.BootstrapMsgType.Success);
                return RedirectToAction(nameof(Index));
            }
            return NotFound();
        }

        private bool CommentExists(int id)
        {
            return _context.Comment.Any(e => e.Id == id);
        }
    }
}

IssueManager/Controllers/IssuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IssueManager.Data;
using IssueManager.Models;
using IssueManager.Static_classes;
using X.PagedList;

namespace IssueManager.Controllers
{
    public class IssuesController : Controller
    {
        private readonly IssueManagerContext _context;

        public IssuesController(IssueManagerContext context)
        {
            _context = context;
        }

        public enum EIssuesSort
        {
            AUTHOR,
            AUTHOR_DESC,
            TITLE,
            TITLE_DESC,
            STATUS,
            STATUS_DESC,
        }

        public static readonly Dictionary<string, EIssuesSort> SortOptionsStringToEnum = new() {
            { "author", EIssuesSort.AUTHOR },
            { "author_desc", EIssuesSort.AUTHOR_DESC },
            { "title", EIssuesSort.TITLE },
            { "title_desc", EIssuesSort.TITLE_DESC },
            { "status", EIssuesSort.STATUS },
            { "status_desc", EIssuesSort.STATUS_DESC },
        };

        public static readonly Dictionary<EIssuesSort, string> SortOptionsEnumToString = SortOptionsStringToEnum.ToDictionary(kvp => kvp.Value, kvp => kvp.Key);

        public static readonly EIssuesSort SortOptionsDefault = EIssuesSort.TITLE;
        public static readonly string SortOptionsDefaultString = SortOptionsEnumToString.GetValueOrDefault(SortOptionsDefault);

        private static EIssuesSort? GetSortFromString(string sort) // may be empty
        {
            if (string.IsNullOrEmpty(sort))
            {
                return null;
            }
            return SortOptionsStringToEnum.GetValueOrDefault(sort, SortOptionsDefault);
        }

        private enum EColumnSortStatus
        {
            Absent,
            Asc,
            Desc
        }
        // GET: Issues
        public async Task<IActionResult> Index(int? projectId, string search, string sort, string currentFilter, int? page)
        {
            ViewData["search"] = search;
            ViewData["projectId"] = projectId;
            // providing this value here instead of determining it in view, because view cannot do it if there isn't any project in result sequence
            ViewData["projectName"] = projectId is null ? "All projects" : _context.Project.Find(projectId).Name;

            if (search != null)
            {
                page = 1;
            }
            else
            {
                search = currentFilter;
            }
            ViewBag.currentFilter = search;
            ViewBag.currentSort = sort;
            
            IQueryable<Issue> issues = _context.Issue.Where(i =>
                (projectId == null
                    || i.project.Id == projectId)
                && (string.IsNullOrEmpty(search) || i.Description.Contains(search)))
                .Include(i => i.Comments).Include(i => i.project);

            var sortType = GetSortFromString(sort);
            EColumnSortStatus authorSort = EColumnSortStatus.Absent, titleSort = EColumnSortStatus.Absent, statusSort = EColumnSortStatus.Absent;
            switch (sortType)
            {
                case EIssuesSort.AUTHOR:
                    issues = issues.OrderBy(i => i.Author);
                    authorSort = EColumnSortStatus.Asc;
                    break;
                case EIssuesSort.AUTHOR_DESC:
                    issues = issues.OrderByDescending(i => i.Author);
                    authorSort = EColumnSortStatus.Desc;
                    break;
                case EIssuesSort.TITLE:
                    issues = issues.OrderBy(i => i.Title);
                    titleSort = EColumnSortStatus.Asc;
                    break;
                case EIssuesSort.TITLE_DESC:
                    issues = issues.OrderByDescending(i => i.Title);
                    titleSort = EColumnSortStatus.Desc;
                    break;
                case EIssuesSort.STATUS:
                    issues = issues.OrderBy(i => i.Status);
                    statusSort = EColumnSortStatus.Asc;
                    break;
                case EIssuesSort.STATUS_DESC:
                    issues = issues.OrderByDescending(i => i.Status);
                    statusSort = EColumnSortStatus.Desc;
                    break;
                case null:
                default:
                    issues = issues.OrderBy(i => i.Title);
                    break;
            }

            // fill view bag with what to sort with
            ViewBag.authorSort = authorSort == EColumnSortStatus.Asc ? "author_desc" : "author";
            ViewBag.titleSort = titleSort == EColumnSortStatus.Asc ? "title_desc" : "title";
            ViewBag.statusSort = statusSort == EColumnSortStatus.Asc ? "status_desc" : "status";

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            var list = issues.ToPagedList(pageNumber, pageSize);
            return View(list);
        }
//

        // GET: Issues/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var issue = await _context.Issue
                .Include(i => i.project)
                .Include(i => i.Comments)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (issue == null)
            {
                return NotFound();
            }

            return View(issue);
        }

        // GET: Issues/Create
        public IActionResult Create(int? projectId)
        {
            if (projectId is null)
            {
                //this.SetTemporaryMessage("Cannot create an dbIssue not referencing any project. Go to projects page, select issues from there, and try again.", Constants.BootstrapMsgType.Danger);
                //return RedirectToAction(nameof(Index));
            }
            ViewData["projectId"] = projectId;
            ViewBag.Projects = _context.Project.Select(p => new SelectListItem { Value = p.Id.ToString(), Text = p.Name }).ToList();
            return View();
        }

        // POST: Issues/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        // values that are assigned below are omitted from bind list
        public async Task<IActionResult> Create([Bind("Title,Description,Author")] Issue issue)
        {
            if (!int.TryParse(Request.Form["project.Id"], out int projectId))
            {
                this.SetTemporaryMessage("Invalid project id", Constants.BootstrapMsgType.Danger);
                return View(issue);
            }
            if (new[] {nameof(Issue.Title), nameof(Issue.Description), nameof(Issue.Author)}.All(s => ModelState.IsFieldValid(s)))
            {
                issue.SubmitDate = DateTime.Now;
                issue.LastUpdateDate = DateTime.Now;
                issue.CloseDate = null;
                issue.Status = IssueStatus.SUBMITTED;
                issue.project = _context.Project.FindAsync(projectId).Result;
                _context.Add(issue);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index), new{ projectId });
        }

        // GET: Issues/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var issue = await _context.Issue.FindAsync(id);
            if (issue == null)
            {
                return NotFound();
            }
            return View(issue);
        }

        // POST: Issues/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        // SubmitDate CloseDate and LastUpdateDate intentionally omitted from the bind list
        public async Task<IActionResult> Edit(int id, [Bind("Title,Description,Author,Status")] Issue issue)
        {
            ModelState.Clear(); // we don't care about validation of part of data, we validate the whole entity later
            //             if (dbIssue.Status == null)
            //             {
            //                 ModelState.AddModelError("Status", "Status is required");
            //             }
            /*else */
            if (!Enum.IsDefined(typeof(IssueStatus), issue.Status))
            {
                ModelState.AddModelError("Status", "Invalid status");
            }

            // find an entity with original id passed in url
            var originalIssue = await _context.Issue.Include(i => i.project).Include(i => i.Comments).SingleAsync(i => i.Id == id);
            if (originalIssue == null)
            {
                return NotFound();
            }
            originalIssue.Author = issue.Author;
            originalIssue.Title = issue.Title;
            originalIssue.Description = issue.Description;
            originalIssue.Status = issue.Status;
            if (originalIssue.Status == IssueStatus.CLOSED)
            {
                originalIssue.CloseDate = DateTime.Now;
            }
            else
            {
                originalIssue.CloseDate = null;
            }
            // every edit action updates the LastUpdateDate
            originalIssue.LastUpdateDate = DateTime.Now;
            try
            {
                if (!TryValidateModel(originalIssue))
                {
                    TempData["msg"] = "Validation failed";

IssueManager/Views/Issues/Create.cshtml
@model IssueManager.Models.Issue

@{
    ViewData["Title"] = "Submit issue";
}

<h1>Submit issue</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" name="projectId" value="@ViewData["projectId"]" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            @*

            ViewData["projectId"] = projectId;
            ViewBag.Projects = _context.Project.Select(p => new SelectListItem { Value = p.Id.ToString(), Text = p.Name }).ToList();
            *@
            <div class="form-group">
				<label class="control-label">Project</label>
				@Html.DropDownListFor(model => model.project.Id, new SelectList(ViewBag.Projects, "Value", "Text"), string.Empty, new { @class = "form-control" })
				<span asp-validation-for="project.Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

IssueManager/Views/Issues/Delete.cshtml
@model IssueManager.Models.Issue

@{
    ViewData["Title"] = "Delete issue";
}

<h1>Delete issue</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Project name
        </dt>
        <dd class = "col-sm-10">
            <a asp-controller="Projects" asp-action="Details" asp-route-id="@Model.project.Id">@Html.DisplayFor(model => model.project.Name)</a>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SubmitDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SubmitDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CloseDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CloseDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastUpdateDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastUpdateDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <!-- comment list -->
		<dt class="col-sm-2">
			Comments
		</dt>
		<dd class="col-sm-10">
			<ul>
				@foreach (var comment in Model.Comments)
				{
					<li>
						<a asp-controller="Comments" asp-action="Details" asp-route-id="@comment.Id">@comment.Content</a>
					</li>
				}
			</ul>
		</dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

IssueManager/Views/Issues/Details.cshtml
@model IssueManager.Models.Issue

@{
    ViewData["Title"] = "Issue details";
}

<h1>Issue details</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.project.Name)
        </dt>
        <dd class="col-sm-10">
			<a asp-controller="Projects" asp-action="Details" asp-route-id="@Model.project.Id">@Html.DisplayFor(model => model.project.Name)</a>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SubmitDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SubmitDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastUpdateDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastUpdateDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-sm-10">
            <!-- this workaround is needed, because you can't call a method in a lambda expression -->
            @{
                // kinda weird way to access model item's property with @
                var str = Issue.getIssueStatusEnumText((IssueStatus)@Model.Status);
            }
            @Html.DisplayFor(modelItem => str)
        </dd>
        @if (@Model.Status == IssueStatus.CLOSED)
        {
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.CloseDate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.CloseDate)
            </dd>
        }
        <!-- comments list -->
        <dt class="col-sm-2">
			Comments
            </dt>
		<dd class="col-sm-10">
            <table>
                <thead>
					<tr>
						<th>@Html.DisplayNameFor(model => model.Comments[0].Author)</th>
						<th>@Html.DisplayNameFor(model => model.Comments[0].Content)</th>
						<th>@Html.DisplayNameFor(model => model.Comments[0].SubmitDate)</th>
					</tr>
				</thead>
				<tbody>
					@foreach (Comment comment in Model.Comments)
					{
                        string content = comment.Content;
                        bool longerThan100 = content.Length > 100;
                        content = longerThan100 ? content.Substring(0, 100) + "..." : content;
						<tr>
							<td>@Html.DisplayFor(modelItem => comment.Author)</td>
							<td>@Html.ActionLink(comment.Content, "Details", "Comments", new { id = comment.Id }, null)</td>
							<td>@Html.DisplayFor(modelItem => comment.SubmitDate)</td>
						</tr>
					}
				</tbody>
            </table>

		</dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

IssueManager/Views/Issues/Index.cshtml
@model X.PagedList.IPagedList<IssueManager.Models.Issue>
@using X.PagedList.Mvc.Core;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewData["Title"] = "Issue list";
    int? projectId = Convert.ToInt32(ViewData["projectId"]);
    bool singleProject = projectId != null && Model.All(issue => issue.project.Id == projectId);
}

@if (singleProject)
{
	<h1>
		List of issues for project "<a asp-action="Details" asp-controller="Projects" asp-route-id="@projectId">@ViewData["projectName"]</a>"
	</h1>
}
else
{
	<h1>
		List of issues
	</h1>
}

@if (Model.Count == 0)
{
    <br />
    <h2>No issues have been submitted yet</h2>
    <br />
}

<form asp-controller="Issues" asp-action="Index" method="get">
    <p>
        <input type="hidden" name="projectId" value="@ViewData["projectId"]" />
        <input type="text" name="search" value="@ViewData["search"]" placeholder="Search by description" />
        <input type="submit" value="Search" />
    </p>
</form>

<p>
    <a asp-action="Create" asp-route-projectId="@ViewData["projectId"]">Submit new issue</a>
</p>
<table class="table">
    <thead>
        <tr>
            @{
                var baseDict = new Dictionary<string, object> { ["search"] = ViewData["search"] };
                if (!singleProject)
                {
                    // workaround to allow conditionally passing projectId to the link, it's important it's missing entirely, because otherwise it would show issues of project with id = 0
                    // I don't want to deal with route parameters etc.
                    if (ViewData.ContainsKey("projectId") && ViewData["projectId"] != null)
                    {
                        baseDict["projectId"] = Convert.ToInt32(ViewData["projectId"]);
                    }
                    // else not present
                    <th>
                        @Html.ActionLink("Project", "Details", "Projects", baseDict, null)
                    </th>
                }
            }
            <th>
                @Html.ActionLink("Title", "Index", "Issues", baseDict.Append(new("sort", ViewBag.titleSort)), null)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].Description)
            </th>
            <th>
                @{//@Html.DisplayNameFor(model => model.Author)
                }
                @Html.ActionLink("Author", "Index", "Issues", baseDict.Append(new("sort", ViewBag.authorSort)), null)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].SubmitDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].CloseDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].LastUpdateDate)
            </th>
            <th>
                @Html.ActionLink("Status", "Index", "Issues", baseDict.Append(new("sort", ViewBag.statusSort)), null)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            @if (!singleProject)
			{
				<td>
					<a asp-controller="Projects" asp-action="Details" asp-route-id="@item.project.Id">@Html.DisplayFor(modelItem => item.project.Name)</a>
				</td>
			}
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SubmitDate)
            </td>
            <td>
                @if (item.Status == IssueStatus.CLOSED)
                {
                    @Html.DisplayFor(modelItem => item.CloseDate)
                }
                else
                {
                    <text>N/A</text>
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastUpdateDate)
            </td>
            <td>
                <!-- this workaround is needed, because you can't call a method in a lambda expression -->
                @{var str = Issue.getIssueStatusEnumText((IssueStatus)item.Status);}
                @Html.DisplayFor(modelItem => str)
            </td>
            <td>
                <!--
                    <a asp-controller="Issues" asp-action="Index" asp-all-route-data="issuesParam">View project issues (issuesCount)</a> |
                -->
                    @{
                        var commentsParam = new Dictionary<string, string>
                        {
                            { "issueId", item.Id.ToString() }
                        };
                        var commentsCount = (item.Comments ?? new()).Count();
                        // note: to make it not-null we need to use eager loading on Issue list
                    }
                <a asp-controller="Comments" asp-route-id="@item.Id" asp-all-route-data="commentsParam">View comments (@commentsCount)</a> |
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

<!-- setup paging -->
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager((X.PagedList.IPagedList)Model, page => Url.Action("Index",
    new { page, sort = ViewBag.currentSort, currentFilter = ViewBag.currentFilter, projectId = ViewData["projectId"], search = ViewData["search"] }))

<!--<style>ul.pagination > li:after {content: " | ";}</style>-->